# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#

jobs:
  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x86-windows
      jobName: x86_windows

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x64-windows
      jobName: x64_windows

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x64-windows-static
      jobName: x64_windows_static

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: x64-uwp
      jobName: x64_uwp

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: arm64-windows
      jobName: arm64_windows

  - template: windows/azure-pipelines.yml
    parameters:
      triplet: arm-uwp
      jobName: arm_uwp
